### ISSUE TITLE
Some Shrine plugins do not seem to run with shrine-tus

### ISSUE THREAD

**Issue by codezomb** [shrinerb/shrine-tus#4]
Given the following uploader, the `determine_mime_type`, and `add_metadata` plugins do not run. If I do not use the tus plugin, they work as expected. I couldn't find any documentation about this so I thought this to be a bug.

```ruby
require 'tika/app'

class FileUploader < Shrine
  plugin :tus
  plugin :add_metadata
  plugin :moving

  plugin :determine_mime_type, analyzer: -> (io, analyzers) do
    Rails.logger.info '###########################################'
    Rails.logger.info 'determine_mime_type should be in the log'
    Rails.logger.info '###########################################'

    mime_type = analyzers[:file].call(io)
  	mime_type = analyzers[:mime_types].call(io) if mime_type == "text/plain"
  	mime_type
  end

  add_metadata :test do |io, context|
    Rails.logger.info '###########################################'
    Rails.logger.info 'add_metadata should be in the log'
    Rails.logger.info '###########################################'
    {}
  end
end
```

**Comment by janko-m** [comment]
When you do any kind of direct uploads (custom endpoint, S3, tus), Shrine won't extract the metadata automatically, and will instead just use metadata that was set on the client side. This is because, in order to extract metadata, Shrine needs to retrieve the file contents (though `determine_mime_type` and `store_dimensions` plugins usually need just first few kilobytes). And that can potentially be expensive if the file is uploaded to remote storage like S3.

You can enable metadata extraction on attachment assignment by loading the `restore_cached_data` plugin. This is useful if you want to validate the extracted metadata, but it means metadata extraction will happen in the foreground.

```rb
Shrine.plugin :restore_cached_data
```

Alternatively you can use the `refresh_metadata` plugin (which `restore_cached_data` uses internally) to trigger the extraction yourself. Then you could e.g. call it in a background job if you're using it, by putting it in the process step when cached file is uploaded to permanent storage:

```rb
Shrine.plugin :refresh_metadata
```
```rb
process(:store) do |io, context|
  io.tap(&:refresh_metadata!) # return original cached file with extracted metadata
end
```

**Comment by codezomb** [comment]
Thanks for the quick reply! Does this also apply when using shrine-this with option C? The upload location and store location are both mounted on the host and accessible.

**Comment by codezomb** [comment]
Worked like a charm, thanks!

**Comment by janko-m** [comment]
Yes, it's also the case with option C, as Shrine doesn't differentiate between storages, as it avoids storage-specific logic in order for the behaviour to stay the same when switching between different storages.

I will add this note to the documentation.
